export const categoryList = () => [
  'Appliances ',
  'Apps & Games',
  'Arts, Crafts, & Sewing',
  'Automotive Parts & Accessories',
  'Baby',
  'Beauty & Personal Care',
  'Books',
  'CDs & Vinyl',
  'Cell Phones & Accessories',
  'Clothing, Shoes and Jewelry',
  'Collectibles & Fine Art',
  'Computers',
  'Electronics',
  'Garden & Outdoor',
  'Grocery & Gourmet Food',
  'Handmade',
  'Health, Household & Baby Care',
  'Home & Kitchen',
  'Industrial & Scientific',
  'Kindle',
  'Luggage & Travel Gear',
  'Movies & TV',
  'Musical Instruments',
  'Office Products',
  'Pet Supplies',
  'Sports & Outdoors',
  'Tools & Home Improvement',
  'Toys & Games',
  'Video Games',
  'Game Console',
  'Game Controller',
];

export enum CategoriesEnum {
  'Appliances ' = 'Appliances ',
  'Apps & Games' = 'Apps & Games',
  'Arts, Crafts, & Sewing' = 'Arts, Crafts, & Sewing',
  'Automotive Parts & Accessories' = 'Automotive Parts & Accessories',
  'Baby' = 'Baby',
  'Beauty & Personal Care' = 'Beauty & Personal Care',
  'Books' = 'Books',
  'CDs & Vinyl' = 'CDs & Vinyl',
  'Cell Phones & Accessories' = 'Cell Phones & Accessories',
  'Clothing, Shoes and Jewelry' = 'Clothing, Shoes and Jewelry',
  'Collectibles & Fine Art' = 'Collectibles & Fine Art',
  'Computers' = 'Computers',
  'Electronics' = 'Electronics',
  'Garden & Outdoor' = 'Garden & Outdoor',
  'Grocery & Gourmet Food' = 'Grocery & Gourmet Food',
  'Handmade' = 'Handmade',
  'Health, Household & Baby Care' = 'Health, Household & Baby Care',
  'Home & Kitchen' = 'Home & Kitchen',
  'Industrial & Scientific' = 'Industrial & Scientific',
  'Kindle' = 'Kindle',
  'Luggage & Travel Gear' = 'Luggage & Travel Gear',
  'Movies & TV' = 'Movies & TV',
  'Musical Instruments' = 'Musical Instruments',
  'Office Products' = 'Office Products',
  'Pet Supplies' = 'Pet Supplies',
  'Sports & Outdoors' = 'Sports & Outdoors',
  'Tools & Home Improvement' = 'Tools & Home Improvement',
  'Toys & Games' = 'Toys & Games',
  'Video Games' = 'Video Games',
  'Game Console' = 'Game Console',
  'Game Controller' = 'Game Controller',
}
