export enum CrudModuleTokens {
  RESOURCE_NAME = 'CRUD_MODULE_RESOURCE_NAME',
  DATA_SERVICE = 'CRUD_MODULE_DATA_SERVICE',
  FORM_OPTIONS = 'CRUD_MODULE_CREATE_FORM_OPTIONS',
  GUARD = 'CRUD_MODULE_GUARD',
  TABLE_OPTIONS = 'CRUD_MODULE_TABLE_OPTIONS',

  TOOLBAR_OPTIONS = 'CRUD_MODULE_TOOLBAR_OPTIONS',

  VIEW_TOOLBAR_OPTIONS = 'CRUD_MODULE_VIEW_TOOLBAR_OPTIONS',
  CREATE_TOOLBAR_OPTIONS = 'CRUD_MODULE_CREATE_TOOLBAR_OPTIONS',
  UPDATE_TOOLBAR_OPTIONS = 'CRUD_MODULE_UPDATE_TOOLBAR_OPTIONS',
  DELETE_TOOLBAR_OPTIONS = 'CRUD_MODULE_DELETE_TOOLBAR_OPTIONS',
}
