
export enum CrudModuleTokens {
  DATA_SERVICE = 'CRUD_MODULE_DATA_SERVICE',
  FORM_OPTIONS = 'CRUD_MODULE_CREATE_FORM_OPTIONS',
  GUARD = 'CRUD_MODULE_GUARD',
  TABLE_OPTIONS = 'CRUD_MODULE_TABLE_OPTIONS'
}
